"""add user_id to invoices

Revision ID: 2bf9fbfbb95b
Revises: ad076f9e2848
Create Date: 2026-09-10 20:41:12.649680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf9fbfbb95b'
down_revision: Union[str, Sequence[str], None] = 'ad076f9e2848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('user_id', sa.Integer(), nullable=True))    
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'])
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'user_id')
    # ### end Alembic commands ###
