"""add user_id to clients

Revision ID: 64ec13354561
Revises: 77ed91522201
Create Date: 2026-09-10 19:43:35.061487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ec13354561'
down_revision: Union[str, Sequence[str], None] = '77ed91522201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'clients',
        sa.Column('user_id', sa.Integer(), nullable=True)
    )

    op.execute("UPDATE clients SET user_id = 1 WHERE user_id IS NULL")

    op.alter_column('clients', 'user_id', nullable=False)

    op.create_foreign_key(
        None,
        'clients',
        'users',
        ['user_id'],
        ['id']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###
